name: Go

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23'

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...

    - name: Go Format
      run: gofmt -s -w . && git diff --exit-code

    - name: Go Vet
      run: go vet ./...

    - name: Go Tidy
      run: go mod tidy && git diff --exit-code

    - name: Go Mod
      run: go mod download

    - name: Go Mod Verify
      run: go mod verify

    - name: Go Generate
      run: go generate ./... && git diff --exit-code

    - name: Go Build
      run: go build -o /dev/null ./...

    - name: Go Compile Tests
      if: github.env.skipTests == 'true'
      run: go test -exec /bin/true ./...

    - name: Go Test
      if: github.env.skipTests != 'true'
      run: go test -v -count=1 -race -shuffle=on -coverprofile=coverage.txt ./...

    - name: Go Benchmark
      if: github.env.skipTests != 'true'
      run: go 
